version: '3.8'

services:
  spring:
    image: mohamedaminederouiche05/spring
    ports:
      - "8082:8080"
    environment:
      - NEXUS_URL=http://192.168.1.23:8081/
      - NEXUS_REPOSITORY=twin6-scriptSquad-foyer
      - NEXUS_USERNAME=admin
      - NEXUS_PASSWORD=nexus
      - ARTIFACT_PATH=com/example/twin6scriptsquadfoyer/0.0.1-SNAPSHOT/twin6scriptsquadfoyer-0.0.1-20240327.035836-18.jar
    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:5.6"
    container_name: my-dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3305:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - /home/vagrant/Prometheus.yml:/etc/prometheus/Prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  db:
