version: '3.8'

services:
  spring:
    image: mohamedaminederouiche/spring
    ports:
      - "8082:8080"
    environment:
      - NEXUS_URL=http://192.168.1.23:8081/
      - NEXUS_REPOSITORY=twin6-scriptSquad-foyer
      - NEXUS_USERNAME=admin
      - NEXUS_PASSWORD=nexus
      - ARTIFACT_PATH=com/example/twin6scriptsquadfoyer/0.0.1-SNAPSHOT/twin6scriptsquadfoyer-0.0.1-20240325.233457-5.jar