version: '3.8'

services:
  spring:
    image: karraymahdi/spring
    ports:
      - "8082:8080"
    environment:
      - NEXUS_URL=http://192.168.33.10:8081/
      - NEXUS_REPOSITORY=twin6-scriptSquad-foyer
      - NEXUS_USERNAME=admin
      - NEXUS_PASSWORD=201JMt4720
      - ARTIFACT_PATH=com/example/4twin6-ScriptSquad-Foyer/0.0.1-SNAPSHOT/twin6scriptsquadfoyer-0.0.1.jar
    depends_on:
      - dbmysql

  dbmysql:
        image: "mysql:5.6"
        container_name: dbmysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - "3305:3306"
        restart: unless-stopped
        volumes:
          - db:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"  # Specify ports as strings
    volumes:
      - /home/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"  # Specify ports as strings
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=esprit
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
  db:
