version: '3.8'
services:
  spring:
    image: ferjaniwael2000/spring
    ports:
      - "8083:8083"  # Specify ports as strings
    environment:
      - NEXUS_URL=http://172.16.6.254:8081/
      - NEXUS_REPOSITORY=twin6-scriptSquad-foyer
      - NEXUS_USERNAME=admin
      - NEXUS_PASSWORD=admin
      - ARTIFACT_PATH=com/example/twin6scriptsquadfoyer/0.0.1-SNAPSHOT/twin6scriptsquadfoyer-0.0.1-20240413.152359-2.jar
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/brogramDB?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - dbmysql
  dbmysql:
    image: "mysql:5.6"
    container_name: my-dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3305:3306"  # Specify ports as strings
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql   # Reference the named volume 'db'
volumes:
  db:  # Define the named volume 'db'

#   prometheus:
#     image: prom/prometheus
#     ports:
#       - "9091:9090"  # Specify ports as strings
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#   grafana:
#     image: grafana/grafana
#     ports:
#       - "3001:3000"  # Specify ports as strings
#     environment:
#       - GF_SECURITY_ADMIN_PASSWORD=grafana
#     volumes:
#       - grafana_data:/var/lib/grafana
#volumes:
#   grafana_data:
#   db: